[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
autonomi = "0.3.6"
axum = "0.8.1"
axum-test = "17.2.0"
serde = "1.0.218"
serde_json = "1.0.140"
tokio = {version="1.43.0", features = ["full"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

